use super::*;

impl Sbc {
    /// Handle incoming SIP response (from trunk/callee) — relay back to caller
    pub(crate) async fn handle_response(
        &mut self,
        response: Response,
        source: SocketAddr,
        _transport: rsip::Transport,
    ) -> Result<()> {
        let status = response.status_code.code();
        info!("Handling {} response from {}", status, source);

        // ── Metrics: count SIP responses + error classes ──
        self.metrics.inc_sip_response(status);
        if status >= 400 && status < 500 {
            self.metrics.sip_4xx_total.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        } else if status >= 500 {
            self.metrics.sip_5xx_total.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        }

        // Extract Call-ID to find associated B2BUA call
        let call_id = response.call_id_header()
            .ok()
            .map(|h| h.value().to_string())
            .unwrap_or_default();

        info!("Response Call-ID: {}", call_id);

        // ── Route outbound REGISTER / OPTIONS health-check responses ──
        // Trunk REGISTER responses use "reg-" Call-IDs, OPTIONS health checks
        // use "hc-" Call-IDs; both are awaited on a oneshot channel by their
        // respective background task via pending_register_responses.
        if call_id.starts_with("reg-") || call_id.starts_with("hc-") {
            if let Some((_, tx)) = self.pending_register_responses.remove(&call_id) {
                let raw = rsip::SipMessage::Response(response).to_string();
                let _ = tx.send(raw);
                debug!("Routed trunk task response (Call-ID: {}) to waiting task", call_id);
            } else {
                debug!("No pending channel for Call-ID: {} (stale or already consumed)", call_id);
            }
            return Ok(());
        }

        if let Some(uuid) = self.b2bua.find_by_inbound_call_id(&call_id).await {
            // Get caller's reply info before processing the response
            let caller_info = self.b2bua.get_caller_reply_info(&uuid).await;

            match status {
                100..=199 => {
                    // Provisional (180 Ringing, 183 Session Progress, etc.) — relay to caller
                    let _ = self.b2bua.handle_ringing(&uuid).await;
                    info!("B2BUA: relaying {} to caller", status);
                    if let Some((reply_tx, caller_addr, caller_transport)) = caller_info {
                        // ── CRITICAL: Restore caller's original Via headers ──────
                        // The response from the callee has the SBC's outbound Via.
                        // The caller will drop it because the branch doesn't match.
                        // We MUST replace the Via with the caller's original Via.
                        let caller_vias = self.b2bua.get_caller_vias(&uuid).await;
                        let raw = rsip::SipMessage::Response(response).to_string();
                        let raw = rewrite_response_for_caller(&raw, &caller_vias, self.identity.as_ref());

                        // ── WebRTC: strip SDP body from 183 Session Progress ────
                        // The trunk sends PCMA/AVP SDP in 183 which is incompatible
                        // with the browser's WebRTC PeerConnection. The real WebRTC
                        // SDP answer is generated by the SBC in the 200 OK handler.
                        let raw = if status == 183 && self.b2bua.is_caller_webrtc(&uuid).await {
                            strip_sdp_body(&raw)
                        } else {
                            raw
                        };

                        let _ = self.transport.reply(raw.as_bytes(), caller_addr, caller_transport, reply_tx.as_ref()).await;
                    }
                }
                200..=299 => {
                    // Final success (200 OK) — rewrite SDP + relay to caller + start RTP proxy
                    let callee_tag = response.to_header()
                        .ok()
                        .and_then(|h| h.typed().ok())
                        .and_then(|to: rsip::typed::To| {
                            to.params.iter().find_map(|p| {
                                if let rsip::Param::Tag(t) = p { Some(t.value().to_string()) } else { None }
                            })
                        })
                        .unwrap_or_default();

                    let callee_sdp_str = if !response.body.is_empty() {
                        std::str::from_utf8(&response.body).ok().map(|s| s.to_string())
                    } else {
                        None
                    };

                    // ── Gather info BEFORE taking the B2BUA lock ──────────────────────
                    // Read caller_sdp and media_id while the lock is NOT yet held
                    // (handle_200_ok will acquire it; avoid deadlock with calls_locked)
                    let (caller_sdp_str_pre, media_id_pre) = {
                        let calls = self.b2bua.calls_locked().await;
                        let c = calls.get(&uuid);
                        let csdp = c.and_then(|c| c.caller_sdp.clone());
                        let mid  = c.and_then(|c| c.media_session_id.clone());
                        (csdp, mid)
                    };

                    let _ = self.b2bua.handle_200_ok(&uuid, callee_tag, callee_sdp_str.clone()).await;

                    // ── Capture established dialog identity (raw From/To/Contact) ──
                    // The 200 OK's To carries the callee tag; From matches our
                    // outbound INVITE. Needed for synthetic in-dialog requests.
                    {
                        let from_raw = response.from_header().ok().map(|h| h.value().to_string());
                        let to_raw = response.to_header().ok().map(|h| h.value().to_string());
                        let callee_contact = response
                            .contact_header()
                            .ok()
                            .map(|h| super::invite_handler_contact_uri(h.value()));
                        if let (Some(from_raw), Some(to_raw)) = (from_raw, to_raw) {
                            self.b2bua
                                .set_established_dialog(&uuid, from_raw, to_raw, callee_contact)
                                .await;
                        }
                    }

                    // ── Start RTP proxy after 200 OK ───────────────────────────────────
                    // Guard: only start once (200 OK retransmissions must not re-bind ports)
                    if let Some(media_id) = media_id_pre {
                        let rtp_already_started = self.media.get_session(&media_id)
                            .map(|s| s.rtp_shutdown_tx.is_some())
                            .unwrap_or(false);

                        if rtp_already_started {
                            debug!("RTP proxy already running for {} — skipping (200 OK retransmit)", media_id);
                        } else {
                            // First 200 OK for this session — count as connected
                            self.metrics.inc_call_connected();

                            // Get caller's public IP (from the TLS/TCP/UDP connection source)
                            // and callee's public IP. These override private IPs from SDP.
                            let (caller_public_ip, callee_public_ip) = {
                                let calls = self.b2bua.calls_locked().await;
                                let c = calls.get(&uuid);
                                let caller_ip = c.map(|c| c.caller_source.ip());
                                let callee_ip = c.and_then(|c| c.callee_dest.map(|d| d.ip()));
                                (caller_ip, callee_ip)
                            };

                            // Configure endpoints from SDP so relay knows where to send RTP.
                            // IMPORTANT: if the SDP IP is a private/NAT address,
                            // replace it with the public IP seen on the signaling connection.
                            //
                            // For WebRTC callers: do NOT pre-configure endpoint A from SDP.
                            // The browser's RTP address is discovered via ICE (STUN binding
                            // requests on the RTP port), not from the SIP signaling address.
                            let caller_is_webrtc_ep = self.b2bua.is_caller_webrtc(&uuid).await;
                            if caller_is_webrtc_ep {
                                info!("RTP proxy: WebRTC caller — endpoint A will be learned via ICE/STUN (not pre-set from SDP)");
                            } else if caller_sdp_str_pre.is_none() {
                                warn!("No caller SDP available — caller endpoint A will be learned dynamically");
                            } else if let Some(ref csdp) = caller_sdp_str_pre {
                                if let Some(sdp_addr) = extract_sdp_rtp_addr(csdp) {
                                    // Use public IP if SDP has private IP (NAT traversal)
                                    let addr = if is_private_ip(sdp_addr.ip()) {
                                        if let Some(public_ip) = caller_public_ip {
                                            let fixed = SocketAddr::new(public_ip, sdp_addr.port());
                                            info!("RTP proxy: caller endpoint A = {} (NAT: SDP had {})", fixed, sdp_addr);
                                            fixed
                                        } else {
                                            info!("RTP proxy: caller endpoint A = {} (from SDP)", sdp_addr);
                                            sdp_addr
                                        }
                                    } else {
                                        info!("RTP proxy: caller endpoint A = {}", sdp_addr);
                                        sdp_addr
                                    };
                                    let _ = self.media.set_endpoint_a(&media_id, addr);
                                }
                            }

                            // Endpoint B = callee's RTP IP:port (from the 200 OK SDP)
                            // For WebRTC callees: do NOT pre-configure endpoint B from SDP.
                            // The browser's RTP address is discovered via ICE (STUN binding
                            // requests on the RTP port), not from the SIP signaling address.
                            let callee_is_webrtc_ep = self.b2bua.is_callee_webrtc(&uuid).await;
                            if callee_is_webrtc_ep {
                                info!("RTP proxy: WebRTC callee — endpoint B will be learned via ICE/STUN (not pre-set from SDP)");
                            } else if let Some(ref bsdp) = callee_sdp_str {
                                if let Some(sdp_addr) = extract_sdp_rtp_addr(bsdp) {
                                    let addr = if is_private_ip(sdp_addr.ip()) {
                                        if let Some(public_ip) = callee_public_ip {
                                            let fixed = SocketAddr::new(public_ip, sdp_addr.port());
                                            info!("RTP proxy: callee endpoint B = {} (NAT: SDP had {})", fixed, sdp_addr);
                                            fixed
                                        } else {
                                            info!("RTP proxy: callee endpoint B = {} (from SDP)", sdp_addr);
                                            sdp_addr
                                        }
                                    } else {
                                        info!("RTP proxy: callee endpoint B = {}", sdp_addr);
                                        sdp_addr
                                    };
                                    let _ = self.media.set_endpoint_b(&media_id, addr);
                                }
                            }

                            // ── Store callee SDP for codec analysis / transcoding ──
                            if let Some(ref csdp) = callee_sdp_str {
                                self.media.set_callee_sdp(&media_id, csdp);
                            }

                            // ── Pass ICE password to MediaManager for STUN MESSAGE-INTEGRITY ──
                            if caller_is_webrtc_ep {
                                if let Some(pwd) = self.b2bua.get_webrtc_ice_pwd(&uuid).await {
                                    self.media.set_ice_pwd_local(&media_id, pwd);
                                }
                            }

                            // ── SRTP extraction DISABLED ──────────────────────────
                            // The SBC relays (S)RTP packets as opaque bytes.
                            // It does NOT participate in SRTP key negotiation
                            // (no a=crypto: in SDP answers), so attempting to
                            // decrypt would fail and drop all audio packets.
                            // Both endpoints negotiate SRTP between themselves
                            // via the forwarded SDP crypto attributes.

                            // Start the RTP relay task (bidirectional A↔B relay)
                            match self.media.start_rtp_session(&media_id).await {
                                Ok((webrtc_info, webrtc_info_b)) => {
                                    info!("RTP proxy started for media session {}", media_id);
                                    self.metrics.set_allocated_ports(self.media.stats().allocated_ports as u64);

                                    // ── Spawn DTLS handshake if caller is WebRTC (leg-A) ──
                                    if let Some(winfo) = webrtc_info {
                                        // Get the WebRTC session (contains DtlsContext)
                                        let webrtc_session = self.b2bua.get_webrtc_session(&uuid).await;
                                        if let Some(ws) = webrtc_session {
                                            let media_id_dtls = media_id.clone();
                                            let srtp_recv_shared = winfo.srtp_recv_ctx_a;
                                            let srtp_send_shared = winfo.srtp_send_ctx_a;

                                            // Pre-generate WebRTC SDP answer BEFORE spawning DTLS task.
                                            // The DTLS task holds the WebRtcSession lock for 15s+ during
                                            // handshake, which would block the 200 OK relay if we tried
                                            // to generate the SDP later.
                                            {
                                                let leg_a_port = self.media.get_session(&media_id)
                                                    .map(|s| s.ports.rtp)
                                                    .unwrap_or(10000);
                                                let sbc_ip = self.identity.as_ref()
                                                    .map(|id| id.public_ip.clone())
                                                    .unwrap_or_else(|| "127.0.0.1".to_string());
                                                let sess = ws.lock().await;
                                                let sdp_answer = sess.generate_sdp_answer(leg_a_port, &sbc_ip);
                                                drop(sess);
                                                self.b2bua.set_webrtc_sdp_answer(&uuid, sdp_answer).await;
                                            }

                                            info!("Spawning DTLS handshake task for call {} (media {})", uuid, media_id_dtls);

                                            tokio::spawn(async move {
                                                // Create the DTLS-UDP bridge
                                                let bridge = Arc::new(DtlsUdpBridge::new(
                                                    winfo.dtls_rx,
                                                    winfo.rtp_socket_a,
                                                    winfo.local_addr,
                                                ));

                                                // Perform the real DTLS handshake
                                                let sess = ws.lock().await;
                                                match sess.dtls_context.perform_handshake(bridge).await {
                                                    Ok(()) => {
                                                        info!("DTLS handshake complete for media session {}", media_id_dtls);

                                                        // Create SRTP contexts from DTLS keys
                                                        match sess.dtls_context.create_srtp_contexts().await {
                                                            Ok((recv_ctx, send_ctx)) => {
                                                                // Hot-swap: inject SRTP contexts into the running relay task.
                                                                // recv_ctx: decrypts incoming SRTP from browser (client keys)
                                                                // send_ctx: encrypts outgoing RTP to browser (server keys)
                                                                *srtp_recv_shared.lock().await = Some(recv_ctx);
                                                                *srtp_send_shared.lock().await = Some(send_ctx);
                                                                info!("DTLS-SRTP hot-swap complete for media session {} — audio should flow", media_id_dtls);
                                                            }
                                                            Err(e) => {
                                                                error!("Failed to create SRTP contexts from DTLS keys: {}", e);
                                                            }
                                                        }
                                                    }
                                                    Err(e) => {
                                                        error!("DTLS handshake failed for media session {}: {}", media_id_dtls, e);
                                                    }
                                                }
                                            });
                                        }
                                    }

                                    // ── Spawn DTLS handshake if callee is WebRTC (leg-B) ──
                                    if let Some(winfo_b) = webrtc_info_b {
                                        let webrtc_session_b = self.b2bua.get_webrtc_session_b(&uuid).await;
                                        if let Some(ws_b) = webrtc_session_b {
                                            let media_id_dtls_b = media_id.clone();
                                            let srtp_recv_shared_b = winfo_b.srtp_recv_ctx_b;
                                            let srtp_send_shared_b = winfo_b.srtp_send_ctx_b;

                                            info!("Spawning DTLS handshake task for call {} leg-B (media {})", uuid, media_id_dtls_b);

                                            tokio::spawn(async move {
                                                let bridge = Arc::new(DtlsUdpBridge::new(
                                                    winfo_b.dtls_rx,
                                                    winfo_b.rtp_socket_b,
                                                    winfo_b.local_addr,
                                                ));

                                                let sess = ws_b.lock().await;
                                                match sess.dtls_context.perform_handshake(bridge).await {
                                                    Ok(()) => {
                                                        info!("DTLS handshake complete for leg-B media session {}", media_id_dtls_b);

                                                        match sess.dtls_context.create_srtp_contexts().await {
                                                            Ok((recv_ctx, send_ctx)) => {
                                                                *srtp_recv_shared_b.lock().await = Some(recv_ctx);
                                                                *srtp_send_shared_b.lock().await = Some(send_ctx);
                                                                info!("DTLS-SRTP hot-swap complete for leg-B media session {} — audio should flow", media_id_dtls_b);
                                                            }
                                                            Err(e) => {
                                                                error!("Failed to create SRTP contexts from DTLS keys (leg-B): {}", e);
                                                            }
                                                        }
                                                    }
                                                    Err(e) => {
                                                        error!("DTLS handshake failed for leg-B media session {}: {}", media_id_dtls_b, e);
                                                    }
                                                }
                                            });
                                        }
                                    }
                                }
                                Err(e) => warn!("Failed to start RTP proxy for {}: {}", media_id, e),
                            }
                        }
                    }

                    info!("B2BUA: relaying 200 OK to caller");
                    if let Some((reply_tx, caller_addr, caller_transport)) = caller_info {
                        // Rewrite SDP in 200 OK body before relaying to caller:
                        // Replace callee's private IP+port with SBC's public IP + leg-B proxy port.
                        // Leg-B port is what the caller will send RTP to (callee side of the proxy).
                        let mut response_to_relay = response;

                        // ── Phase 13: Process callee WebRTC INDEPENDENTLY of caller type ──
                        // When callee is WebRTC, we MUST set_remote_sdp() on leg-B session
                        // regardless of whether the caller is also WebRTC. Previously this
                        // was inside an `else` branch and skipped for WebRTC→WebRTC calls.
                        let callee_is_webrtc = self.b2bua.is_callee_webrtc(&uuid).await;
                        if callee_is_webrtc && !response_to_relay.body.is_empty() {
                            if let Ok(callee_webrtc_sdp) = std::str::from_utf8(&response_to_relay.body) {
                                info!("200 OK from WebRTC callee — SDP:\n{}", callee_webrtc_sdp);

                                // Set remote SDP on the WebRTC session for leg-B (DTLS needs this)
                                let ws_b = self.b2bua.get_webrtc_session_b(&uuid).await;
                                if let Some(ws) = ws_b {
                                    let mut sess = ws.lock().await;
                                    sess.set_remote_sdp(callee_webrtc_sdp);
                                    drop(sess);
                                    info!("WebRTC session B: remote SDP set from callee 200 OK");
                                }
                            }
                        }

                        // ── Decide which SDP to send to the caller ──
                        let is_webrtc_call = self.b2bua.is_caller_webrtc(&uuid).await;

                        // Log both-WebRTC calls for Phase 13 debugging
                        if is_webrtc_call && callee_is_webrtc {
                            info!("WebRTC ↔ WebRTC call detected — Opus passthrough, dual DTLS-SRTP");
                        }

                        if is_webrtc_call {
                            // WebRTC caller: use the pre-generated SDP answer (Opus/SAVPF/DTLS/ICE)
                            // instead of relaying the callee's SDP directly.
                            // The SDP was pre-generated before the DTLS task was spawned to avoid
                            // deadlock (DTLS task holds the WebRtcSession lock during handshake).
                            let pre_sdp = self.b2bua.get_webrtc_sdp_answer(&uuid).await;
                            if let Some(webrtc_sdp) = pre_sdp {
                                info!("WebRTC SDP answer for browser:\n{}", webrtc_sdp);
                                response_to_relay.body = webrtc_sdp.into_bytes();
                                update_content_length_response(&mut response_to_relay);
                            } else {
                                warn!("WebRTC call {} but no pre-generated SDP answer — falling back to standard SDP rewrite", uuid);
                                // Fallback: standard SDP rewrite
                                if !response_to_relay.body.is_empty() {
                                    if let Ok(sdp_str) = std::str::from_utf8(&response_to_relay.body) {
                                        let media_id = self.b2bua.get_media_session_id(&uuid).await;
                                        let rewritten = if let Some(ref mid) = media_id {
                                            if let Some(session) = self.media.get_session(mid) {
                                                self.media.rewrite_sdp_for_proxy(sdp_str, session.ports.rtp)
                                            } else {
                                                self.media.rewrite_sdp_ip(sdp_str)
                                            }
                                        } else {
                                            self.media.rewrite_sdp_ip(sdp_str)
                                        };
                                        response_to_relay.body = rewritten.into_bytes();
                                        update_content_length_response(&mut response_to_relay);
                                    }
                                }
                            }
                        } else if callee_is_webrtc && !response_to_relay.body.is_empty() {
                            // Caller is NOT WebRTC (PSTN/SIP), callee IS WebRTC:
                            // Transform WebRTC SDP → trunk PCMA/AVP for the non-WebRTC caller.
                            if let Ok(callee_webrtc_sdp) = std::str::from_utf8(&response_to_relay.body) {
                                let sbc_ip = self.identity.as_ref()
                                    .map(|id| id.public_ip.clone())
                                    .unwrap_or_else(|| "127.0.0.1".to_string());
                                let media_id = self.b2bua.get_media_session_id(&uuid).await;
                                let trunk_port = if let Some(ref mid) = media_id {
                                    self.media.get_session(mid)
                                        .map(|s| s.ports.rtp)
                                        .unwrap_or(10000)
                                } else {
                                    10000
                                };
                                let trunk_sdp = transform_webrtc_to_trunk(callee_webrtc_sdp, &sbc_ip, trunk_port);
                                info!("WebRTC→Trunk 200 OK SDP transformation (port {}):\n{}", trunk_port, trunk_sdp);
                                response_to_relay.body = trunk_sdp.into_bytes();
                                update_content_length_response(&mut response_to_relay);
                            }
                        } else if !response_to_relay.body.is_empty() {
                            // Standard SIP caller + standard SIP callee: rewrite SDP with SBC proxy IP+port
                            if let Ok(sdp_str) = std::str::from_utf8(&response_to_relay.body) {
                                let media_id = self.b2bua.get_media_session_id(&uuid).await;
                                let rewritten = if let Some(ref mid) = media_id {
                                    if let Some(session) = self.media.get_session(mid) {
                                        // Use leg-A port: caller sends RTP to leg-A, leg-A relays to callee.
                                        self.media.rewrite_sdp_for_proxy(sdp_str, session.ports.rtp)
                                    } else {
                                        self.media.rewrite_sdp_ip(sdp_str)
                                    }
                                } else {
                                    self.media.rewrite_sdp_ip(sdp_str)
                                };
                                if rewritten != sdp_str {
                                    info!("SDP 200 OK outbound (to caller):\n{}", rewritten);
                                } else {
                                    info!("SDP 200 OK outbound (unchanged):\n{}", rewritten);
                                }
                                response_to_relay.body = rewritten.into_bytes();
                                // Update Content-Length to match new body size (critical for TCP framing)
                                update_content_length_response(&mut response_to_relay);
                            }
                        }
                        // ── CRITICAL: Restore caller's original Via headers ──────
                        // The 200 OK from the callee has the SBC's outbound Via.
                        // The caller will drop it because the branch doesn't match.
                        // We MUST replace the Via with the caller's original Via.
                        let caller_vias = self.b2bua.get_caller_vias(&uuid).await;
                        let raw = rsip::SipMessage::Response(response_to_relay).to_string();
                        let raw = rewrite_response_for_caller(&raw, &caller_vias, self.identity.as_ref());
                        let _ = self.transport.reply(raw.as_bytes(), caller_addr, caller_transport, reply_tx.as_ref()).await;
                    }
                }
                407 => {
                    // ── Proxy Authentication Required from trunk ──────────────
                    // The trunk is challenging us for credentials. We need to:
                    // 1. Extract the Proxy-Authenticate challenge
                    // 2. Look up trunk credentials
                    // 3. Resend the INVITE with Proxy-Authorization
                    info!("B2BUA: received 407 Proxy Auth Required for call {}", uuid);

                    let retry_result = self.handle_407_auth_retry(&uuid, &response, source).await;

                    match retry_result {
                        Ok(true) => {
                            // Successfully resent INVITE with auth — wait for next response
                            info!("B2BUA: retrying INVITE with Proxy-Authorization for call {}", uuid);
                        }
                        Ok(false) | Err(_) => {
                            // Auth retry failed or exhausted — relay error to caller
                            warn!("B2BUA: 407 auth retry failed for call {}, relaying to caller", uuid);
                            if let Some((reply_tx, caller_addr, caller_transport)) = caller_info {
                                let caller_vias = self.b2bua.get_caller_vias(&uuid).await;
                                // Send 503 to caller (don't leak trunk's 407)
                                let response_503 = build_plain_response(503, "Service Unavailable");
                                let raw = rewrite_response_for_caller(&response_503, &caller_vias, self.identity.as_ref());
                                let _ = self.transport.reply(raw.as_bytes(), caller_addr, caller_transport, reply_tx.as_ref()).await;
                            }
                            self.b2bua.terminate_call(&uuid).await;
                            self.metrics.inc_call_failed();
                        }
                    }
                }
                _ => {
                    // Error response (4xx/5xx/6xx) — relay to caller, terminate call
                    info!("B2BUA: relaying error {} to caller, terminating call", status);
                    if let Some((reply_tx, caller_addr, caller_transport)) = caller_info {
                        let caller_vias = self.b2bua.get_caller_vias(&uuid).await;
                        let raw = rsip::SipMessage::Response(response).to_string();
                        let raw = rewrite_response_for_caller(&raw, &caller_vias, self.identity.as_ref());
                        let _ = self.transport.reply(raw.as_bytes(), caller_addr, caller_transport, reply_tx.as_ref()).await;
                    }
                    self.b2bua.terminate_call(&uuid).await;
                    self.metrics.inc_call_failed();
                }
            }
        } else {
            info!("No B2BUA call found for response Call-ID: {} from {} (stray response)", call_id, source);
        }

        Ok(())
    }
}
